# Generated by Django 4.0.2 on 2023-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='areas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
