# Generated by Django 4.0.2 on 2024-01-01 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duties', '0005_alter_routes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStops',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duty_stop', models.CharField(choices=[('not_available', 'Not Available'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='assiged', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
