# Generated by Django 4.0.2 on 2024-01-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0006_dutystops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DutyStops',
        ),
    ]
