# Generated by Django 4.0.2 on 2024-01-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0007_delete_dutystops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='delivered_outlets',
            new_name='delivered_attempted_outlets',
        ),
    ]
