# Generated by Django 4.0.2 on 2024-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0008_rename_delivered_outlets_duty_delivered_attempted_outlets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed')], default='assiged', max_length=10),
        ),
    ]
