# Generated by Django 4.0.2 on 2024-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0009_alter_duty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrants',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
