# Generated by Django 4.0.2 on 2024-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0010_quadrants_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
