# Generated by Django 4.0.2 on 2024-01-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0011_routes_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='pincode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
