# Generated by Django 4.0.2 on 2023-12-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsstock',
            name='purchase_product',
        ),
    ]
