# Generated by Django 4.0.2 on 2023-12-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productsstock_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsstock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
