# Generated by Django 4.0.2 on 2023-12-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productsstock_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproducts',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productsstock',
            name='sale_mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
