# Generated by Django 4.0.2 on 2023-12-31 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_alter_farmerproducts_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproducts',
            name='packaging',
            field=models.CharField(choices=[('kg', 'KG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='packaging',
            field=models.CharField(blank=True, choices=[('kg', 'KG')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='farmerproducts',
            unique_together={('product', 'mrp', 'expiry_date', 'packaging', 'farmer')},
        ),
        migrations.AlterUniqueTogether(
            name='productsstock',
            unique_together={('product', 'sale_mrp', 'expiry_date')},
        ),
    ]
