# Generated by Django 4.0.2 on 2024-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productsstock_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('green_vegies', 'Green Vegies'), ('vegitables', 'Vegetables'), ('salad', 'Salad'), ('fruits', 'Fruits')], max_length=60),
        ),
    ]
