# Generated by Django 4.0.2 on 2024-02-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='cat_images', to='inventory.File'),
        ),
    ]
