# Generated by Django 4.0.2 on 2023-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_b2borders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='delivered_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='received_qty',
            field=models.IntegerField(default=0),
        ),
    ]
