# Generated by Django 4.0.2 on 2023-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproducts_delivered_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borders',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='b2corders',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
