# Generated by Django 4.0.2 on 2023-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_b2borders_collected_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borders',
            name='is_inward_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
