# Generated by Django 4.0.2 on 2023-12-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproducts_farmer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='farmer_product_id',
            new_name='farmer_product',
        ),
    ]
