# Generated by Django 4.0.2 on 2023-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_b2borders_initial_amount_b2corders_initial_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='received_qty',
            new_name='checked_qty',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='return_qty',
            field=models.IntegerField(default=0),
        ),
    ]
