# Generated by Django 4.0.2 on 2023-12-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_received_qty_orderproducts_checked_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2corders',
            old_name='initial_amount',
            new_name='i_v',
        ),
    ]
