# Generated by Django 4.0.2 on 2023-12-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
        ('orders', '0014_rename_initial_amount_b2corders_i_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corders',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_order', to='duties.duty'),
        ),
    ]
