# Generated by Django 4.0.2 on 2024-01-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_b2corders_quadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corders',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
