# Generated by Django 4.0.2 on 2024-01-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_b2corders_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corders',
            name='delivery_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
