# Generated by Django 4.0.2 on 2024-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
