# Generated by Django 4.0.2 on 2024-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderproducts_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corders',
            name='customer_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('ready_to_delivery', 'Ready to Delivery'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('r_a_wh', 'Received at Warehouse')], default='placed', max_length=20),
        ),
    ]
